version: '3.8'

services:
  postgres-petclinic:
    image: postgres:latest
    container_name: postgres-petclinic
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: