version: '3.8'
services:
  postgres:
    image: postgres:16.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_DB: petclinic

  backend:
    image: springcommunity/spring-petclinic-rest:latest
    ports:
      - "9966:9966"
    environment:
      SPRING_PROFILES_ACTIVE: postgres,spring-data-jpa
      POSTGRES_URL: jdbc:postgresql://postgres:5432/petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASS: petclinic
    depends_on:
      - postgres

  frontend:
    build: ./demo-spring-petclinic-angular
    ports:
      - "8080:8080"
    depends_on:
      - backend
