kind: ConfigMap
apiVersion: v1
metadata:
  name: optima-agile-buddy-config
  namespace: optima
data:
  POSTGRES_URL: "jdbc:postgresql://optimadb.cfgy6kwc4e0h.eu-west-1.rds.amazonaws.com:5432/petclinic"
  POSTGRES_USER: "optimadbuser"
  POSTGRES_PASS: "optimadbpassword"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-backend
  namespace: petclinic
  labels:
    app: petclinic-backend
    run: petclinic-backend
spec:
  selector:
    matchLabels:
      run: petclinic-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: petclinic-backend
        run: petclinic-backend
    spec:
      containers:
        - image: 061039780337.dkr.ecr.eu-west-1.amazonaws.com/petclinic/backend:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: petclinic-backend
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 1000m
              memory: 2Gi
          ports:
            - containerPort: 5005
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: petclinic-backend-config
---
kind: Service
apiVersion: v1
metadata:
  name: petclinic-backend
  namespace: petclinic
spec:
  type: NodePort
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: petclinic-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-petclinic-backend
  namespace: petclinic
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "off"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
    nginx.ingress.kubernetes.io/cors-allow-headers: authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT,GET,POST,HEAD,PATCH,DELETE
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: petclinic-backend
                port:
                  number: 80
            path: /petclinic/api
            pathType: Prefix