name: Azure Deploy BE

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "BE: Build and Push Docker Image"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Build with Maven
        shell: bash
        working-directory: demo-spring-petclinic-java
        run: mvn package -DskipTests

      - uses: azure/docker-login@v2
        with:
          login-server: petcliniccr.azurecr.io
          username: 'petcliniccr'
          password: 'vtPkfbiuwXulUNz4N6nn6lfoQ4hXNqDkP9unM/eCIl+ACRAG3Xr5'

      - name: Build and push Docker image
        working-directory: demo-spring-petclinic-java
        shell: bash
        run: |
          docker build -t petcliniccr.azurecr.io/backend:latest .
          docker push petcliniccr.azurecr.io/backend:latest
