name: Azure Deploy FE

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "FE: Build and Push Docker Image"
    outputs:
      IMAGE_VERSION: latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: azure/docker-login@v2
        with:
          login-server: petcliniccr.azurecr.io
          username: 'petcliniccr'
          password: 'xhjVwqqZPz1gXKRmmhpdeaXD34WdYOgRBj/3z4kNdQ+ACRD3TqjH'

      - name: Build and push Docker image
        shell: bash
        working-directory: demo-spring-petclinic-angular
        run: |
          docker build -t petcliniccr.azurecr.io/frontend:${{ env.VERSION }} .
          docker push petcliniccr.azurecr.io/frontend:${{ env.VERSION }}
