name: Azure Deploy FE

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "FE: Build and Push Docker Image"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: petcliniccr.azurecr.io
          username: 'petcliniccr'
          password: 'xhjVwqqZPz1gXKRmmhpdeaXD34WdYOgRBj/3z4kNdQ+ACRD3TqjH'

      - name: Build and Push Docker Image
        working-directory: demo-spring-petclinic-angular
        run: |
          docker build -t petcliniccr.azurecr.io/frontend:${{ github.sha }} .
          docker push petcliniccr.azurecr.io/frontend:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: petclinic-fe
          images: petcliniccr.azurecr.io/frontend:${{ github.sha }}
