name: GCP Deploy FE
on: 
  workflow_dispatch:    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build docker images
      working-directory: ./demo-spring-petclinic-angular/
      run: docker build .
