name: GCP Deploy FE

on:
  workflow_dispatch:

env:
  REGISTRY: europe-north1-docker.pkg.dev/optimum-agent-453312-a2/petclinic-cr

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "FE: Build and Push Docker Image"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Build and push Docker image to GCR
        working-directory: demo-spring-petclinic-angular
        shell: bash
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/petclinic-fe
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy petclinic-fe \
            --image=${{env.REGISTRY}}/petclinic-fe:latest \
            --platform=managed \
            --region=europe-north1