name: GCP Deploy BE
on:
  workflow_dispatch:
    inputs:
      version:
        options:
        - v1
        - v2
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demo-spring-petclinic-java/
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Build docker java
      run: docker build . -t java:${{ github.event.inputs.version }}
    - name: Tag docker images    
      run: docker tag java:${{ github.event.inputs.version }} europe-west10-docker.pkg.dev/optimum-agent-453312-a2/petclinic-be/java:${{ github.event.inputs.version }} 
    - name: Push docker images    
      run: docker push europe-west10-docker.pkg.dev/optimum-agent-453312-a2/petclinic-be/java:${{ github.event.inputs.version }} 